/**
 * @module types
 *
 * Shared TypeScript type definitions for the MentisAI application.
 * Defines the data contracts used across components, hooks, and services
 * including chat messages, sessions, subjects, attachments, and AI config.
 */

/**
 * Identifies the sender of a chat message.
 * - `USER` — message sent by the student.
 * - `MODEL` — response generated by the AI tutor.
 */
export enum Role {
  USER = 'user',
  MODEL = 'model'
}

/**
 * Represents a Firestore server-generated timestamp.
 * Firestore returns this shape instead of a native `Date` until the
 * snapshot is resolved; call `toDate()` to convert.
 */
export interface Timestamp {
  toDate: () => Date;
  seconds: number;
  nanoseconds: number;
}

/**
 * A single chat message exchanged between the user and the AI tutor.
 *
 * @property id          - Firestore document ID.
 * @property role        - Who sent the message (`USER` or `MODEL`).
 * @property content     - The textual content of the message (may contain Markdown/LaTeX).
 * @property timestamp   - When the message was created (native `Date` or Firestore `Timestamp`).
 * @property isStreaming  - If `true`, the message is still being generated (reserved for future streaming support).
 * @property attachment  - Optional file attachment (image or text).
 */
export interface Message {
  id: string;
  role: Role;
  content: string;
  timestamp: Date | Timestamp;
  isStreaming?: boolean;
  attachment?: Attachment;
}

/**
 * File attachment metadata embedded in a {@link Message}.
 *
 * @property content  - Base64-encoded data URI (images) or raw text content (code files).
 * @property type     - Discriminator: `'image'` for visual files, `'text'` for code/text files.
 * @property mimeType - Original MIME type of the uploaded file (e.g. `image/png`).
 * @property fileName - Original filename as provided by the user's file picker.
 */
export interface Attachment {
  content: string;
  type: 'image' | 'text';
  mimeType?: string;
  fileName?: string;
}

/**
 * A persisted chat session stored under `users/{uid}/chats` in Firestore.
 *
 * @property id        - Firestore document ID.
 * @property subject   - The academic subject this session is about.
 * @property title     - AI-generated or user-set title for the chat.
 * @property createdAt - Session creation time.
 * @property messages  - Array of messages in the session (may be populated separately).
 * @property userId    - UID of the owning user.
 */
export interface ChatSession {
  id: string;
  subject: Subject;
  title?: string;
  createdAt: Date | Timestamp;
  messages: Message[];
  userId: string;
}

/**
 * Academic subjects available for tutoring.
 * Determines the AI's system prompt specialization and allowed attachment types.
 */
export enum Subject {
  MATH = 'Math',
  PHYSICS = 'Physics',
  CHEMISTRY = 'Chemistry',
  HISTORY = 'History',
  BIOLOGY = 'Biology',
  LITERATURE = 'Literature',
  CODING = 'Coding',
  GENERAL = 'General'
}

/**
 * Optional configuration overrides for the Gemini generative model.
 *
 * @property temperature - Controls randomness (0 = deterministic, 1 = creative).
 * @property topK        - Limits token sampling to the top-K most probable tokens.
 * @property topP        - Nucleus sampling threshold.
 */
export interface GeminiConfig {
  temperature?: number;
  topK?: number;
  topP?: number;
}